-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Table: Profiles (Extends Supabase Auth)
create table profiles (
  id uuid references auth.users(id) on delete cascade not null primary key,
  email text,
  full_name text,
  occupation text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Routines (Generated by AI)
create table routines (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null, -- e.g., "Morning Revision"
  type text not null, -- 'work', 'study', 'health'
  start_time time not null,
  duration integer not null, -- minutes
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Projects (Perdidão/Kanban)
create table projects (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  status text default 'todo', -- 'todo', 'in_progress', 'done'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table routines enable row level security;
alter table projects enable row level security;

-- Policies (Users can only see/edit their own data)
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

create policy "Users can view own routines" on routines for select using (auth.uid() = user_id);
create policy "Users can create own routines" on routines for insert with check (auth.uid() = user_id);
create policy "Users can update own routines" on routines for update using (auth.uid() = user_id);
create policy "Users can delete own routines" on routines for delete using (auth.uid() = user_id);

create policy "Users can view own projects" on projects for select using (auth.uid() = user_id);
create policy "Users can create own projects" on projects for insert with check (auth.uid() = user_id);
create policy "Users can update own projects" on projects for update using (auth.uid() = user_id);

-- Trigger to create profile on Signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
