-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Table: Profiles (Extends Supabase Auth)
create table if not exists profiles (
  id uuid references auth.users(id) on delete cascade not null primary key,
  email text,
  full_name text,
  occupation text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Routines (Generated by AI)
create table if not exists routines (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null, -- e.g., "Morning Revision"
  type text not null, -- 'work', 'study', 'health'
  start_time time not null,
  duration integer not null, -- minutes
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Projects (Perdidão/Kanban)
create table if not exists projects (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  status text default 'todo', -- 'todo', 'in_progress', 'done'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table routines enable row level security;
alter table projects enable row level security;

-- Policies (Drop first to avoid duplication error on re-run)
drop policy if exists "Users can view own profile" on profiles;
drop policy if exists "Users can update own profile" on profiles;
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

drop policy if exists "Users can view own routines" on routines;
drop policy if exists "Users can create own routines" on routines;
drop policy if exists "Users can update own routines" on routines;
drop policy if exists "Users can delete own routines" on routines;
create policy "Users can view own routines" on routines for select using (auth.uid() = user_id);
create policy "Users can create own routines" on routines for insert with check (auth.uid() = user_id);
create policy "Users can update own routines" on routines for update using (auth.uid() = user_id);
create policy "Users can delete own routines" on routines for delete using (auth.uid() = user_id);

drop policy if exists "Users can view own projects" on projects;
drop policy if exists "Users can create own projects" on projects;
drop policy if exists "Users can update own projects" on projects;
create policy "Users can view own projects" on projects for select using (auth.uid() = user_id);
create policy "Users can create own projects" on projects for insert with check (auth.uid() = user_id);
create policy "Users can update own projects" on projects for update using (auth.uid() = user_id);


-- Table: Subjects (Matérias)
create table if not exists subjects (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  name text not null,
  color text default '#6366f1',
  goal text,
  difficulty integer check (difficulty >= 1 and difficulty <= 5),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Study Materials (Conteúdos)
create table if not exists study_materials (
  id uuid default uuid_generate_v4() primary key,
  subject_id uuid references subjects(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  type text check (type in ('pdf', 'text', 'link', 'video')),
  content text,
  summary text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Flashcards (Revisão)
create table flashcards (
  id uuid default uuid_generate_v4() primary key,
  subject_id uuid references subjects(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  front text not null,
  back text not null,
  next_review timestamp with time zone default now(),
  interval integer default 0,
  ease_factor float default 2.5,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Mind Maps (Mapas Mentais)
create table mindmaps (
  id uuid default uuid_generate_v4() primary key,
  subject_id uuid references subjects(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  nodes jsonb default '[]',
  edges jsonb default '[]',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for new tables
alter table subjects enable row level security;
alter table study_materials enable row level security;
alter table flashcards enable row level security;
alter table mindmaps enable row level security;

-- Policies for Subjects
create policy "Users can view own subjects" on subjects for select using (auth.uid() = user_id);
create policy "Users can create own subjects" on subjects for insert with check (auth.uid() = user_id);
create policy "Users can update own subjects" on subjects for update using (auth.uid() = user_id);
create policy "Users can delete own subjects" on subjects for delete using (auth.uid() = user_id);

-- Policies for Materials
create policy "Users can view own materials" on study_materials for select using (auth.uid() = user_id);
create policy "Users can create own materials" on study_materials for insert with check (auth.uid() = user_id);
create policy "Users can update own materials" on study_materials for update using (auth.uid() = user_id);
create policy "Users can delete own materials" on study_materials for delete using (auth.uid() = user_id);

-- Policies for Flashcards
create policy "Users can view own flashcards" on flashcards for select using (auth.uid() = user_id);
create policy "Users can create own flashcards" on flashcards for insert with check (auth.uid() = user_id);
create policy "Users can update own flashcards" on flashcards for update using (auth.uid() = user_id);
create policy "Users can delete own flashcards" on flashcards for delete using (auth.uid() = user_id);

-- Policies for Mindmaps
create policy "Users can view own mindmaps" on mindmaps for select using (auth.uid() = user_id);
create policy "Users can create own mindmaps" on mindmaps for insert with check (auth.uid() = user_id);
create policy "Users can update own mindmaps" on mindmaps for update using (auth.uid() = user_id);
create policy "Users can delete own mindmaps" on mindmaps for delete using (auth.uid() = user_id);

-- Trigger to create profile on Signup (Existing, unchanged)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Table: User Settings (Perdidão Config)
create table if not exists user_settings (
  user_id uuid references profiles(id) on delete cascade not null primary key,
  wake_up_time time not null default '07:00:00',
  bed_time time not null default '23:00:00',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Fixed Tasks (Compromissos Fixos)
create table if not exists fixed_tasks (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  start_time time not null,
  end_time time not null,
  days_of_week integer[] not null, -- Array of integers (1=Mon, 7=Sun)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table user_settings enable row level security;
alter table fixed_tasks enable row level security;

-- Policies for User Settings
create policy "Users can view own settings" on user_settings for select using (auth.uid() = user_id);
create policy "Users can upsert own settings" on user_settings for insert with check (auth.uid() = user_id) on conflict (user_id) do update set wake_up_time = excluded.wake_up_time, bed_time = excluded.bed_time;
create policy "Users can update own settings" on user_settings for update using (auth.uid() = user_id);

-- Policies for Fixed Tasks
create policy "Users can view own fixed tasks" on fixed_tasks for select using (auth.uid() = user_id);
create policy "Users can create own fixed tasks" on fixed_tasks for insert with check (auth.uid() = user_id);
create policy "Users can update own fixed tasks" on fixed_tasks for update using (auth.uid() = user_id);
create policy "Users can delete own fixed tasks" on fixed_tasks for delete using (auth.uid() = user_id);
